# Generated by Django 5.2.17 on 2026-09-09 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(db_column='startAt')),
                ('duration_min', models.IntegerField(db_column='durationMin', default=60)),
                ('service_type', models.TextField(db_column='serviceType')),
                ('status', models.TextField(default='scheduled')),
                ('deposit_cents', models.IntegerField(db_column='depositCents', default=0)),
                ('deposit_paid', models.BooleanField(db_column='depositPaid', default=False)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Appointment',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('specialty', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Artist',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField(blank=True, default='')),
                ('email', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.TextField(default='[]')),
                ('last_visit', models.DateTimeField(blank=True, db_column='lastVisit', null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Client',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientImage',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('prep_for_visit', models.BooleanField(db_column='prepForVisit', default=False)),
                ('caption', models.TextField(blank=True, default='')),
                ('storage_key', models.TextField(db_column='storageKey')),
                ('mime_type', models.TextField(db_column='mimeType')),
                ('byte_size', models.IntegerField(db_column='byteSize')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
            ],
            options={
                'db_table': 'ClientImage',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('result_id', models.TextField(db_column='resultId')),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'IdempotencyKey',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('shop_id', models.TextField(blank=True, db_column='shopId', null=True)),
                ('session_id', models.TextField(db_column='sessionId')),
                ('surface', models.TextField()),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'PageView',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('amount_cents', models.IntegerField(db_column='amountCents')),
                ('currency', models.TextField(default='usd')),
                ('status', models.TextField(default='pending')),
                ('stripe_session_id', models.TextField(blank=True, db_column='stripeSessionId', null=True)),
                ('stripe_payment_intent_id', models.TextField(blank=True, db_column='stripePaymentIntentId', null=True)),
                ('type', models.TextField()),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Payment',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField(db_column='passwordHash')),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'PlatformUser',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('design_notes', models.TextField(blank=True, db_column='designNotes', default='')),
                ('placement', models.TextField(blank=True, default='')),
                ('ink_colors', models.TextField(blank=True, db_column='inkColors', default='')),
                ('aftercare_given', models.BooleanField(db_column='aftercareGiven', default=False)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'SessionNote',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('timezone', models.TextField(default='America/Los_Angeles')),
                ('hours_open', models.TextField(db_column='hoursOpen', default='11:00')),
                ('hours_close', models.TextField(db_column='hoursClose', default='20:00')),
                ('stripe_publishable_key', models.TextField(blank=True, db_column='stripePublishableKey', default='')),
                ('stripe_secret_key', models.TextField(blank=True, db_column='stripeSecretKey', default='')),
                ('stripe_webhook_secret', models.TextField(blank=True, db_column='stripeWebhookSecret', default='')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, db_column='onboardingCompletedAt', null=True)),
                ('onboarding_step', models.IntegerField(db_column='onboardingStep', default=1)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Shop',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField(db_column='passwordHash')),
                ('name', models.TextField()),
                ('role', models.TextField(default='owner')),
                ('active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_column='lastSeenAt', null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'User',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopAuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='parlor.shopuser')),
            ],
            options={
                'db_table': 'django_shop_auth_token',
            },
        ),
    ]
